spring.application.name=SmartCampusEvent
server.port=8080

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/campus_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=jyothisrinivas@14
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# Logging
logging.level.com.example.event=DEBUG
logging.level.org.springframework.security=INFO

# App Info
app.name=Smart Campus Event Management System
app.version=1.0.0